seml:
  name: msvm_hyperparams
  executable: exp_ntk_hyperparam.py
  project_root_dir: ../..
  output_dir: log/hyperparam

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: phdcpu      
    partition: cpu,cpu_large
    gres: gpu:0       # num gpu
    mem: 20G          # memory
    cpus-per-task: 1  # num cores
    time: 0-01:15     # max time, D-HH:MM

fixed:
  data_params:
    learning_setting: transductive
    cv_folds: 4
    specification:
      n_per_class: 20
      fraction_test: 0.1
      data_dir: ./data
      balance_test: True

  model_params:
    label: GCN
    model: GCN
    normalization: row_normalization
    depth: 1
    solver: MSVM
    bias: False
    alpha_tol: 1e-4

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False

grid:
  
  data_params:
    dataset:
      type: choice
      options:
      - citeseer
      - cora
      - cora_ml
      - cora_ml_cont

  model_params:
    pred_method:
      type: choice
      options:
      - svm

    regularizer:
      type: choice
      options:
      - 0.0001
      - 0.0002
      - 0.0005
      - 0.001
      - 0.00175
      - 0.002
      - 0.0025
      - 0.003
      - 0.0035
      - 0.004
      - 0.0045
      - 0.005
      - 0.0055
      - 0.006
      - 0.0065
      - 0.007
      - 0.0075
      - 0.008
      - 0.0085
      - 0.009
      - 0.0095
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100

  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 10
          step: 1

