seml:
  name: cora_cont_skipalpha
  executable: exp_ntk_hyperparam.py
  project_root_dir: ../..
  output_dir: log/hyperparam

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-00:15     # max time, D-HH:MM

fixed:
  data_params:
    learning_setting: transductive
    cv_folds: 4
    specification:
      n_per_class: 10
      fraction_test: 0.1
      data_dir: ./data
      balance_test: True

  model_params:
    label: GCN_skipalpha
    model: GCN
    activation: relu
    normalization: row_normalization
    depth: 1
    solver: qplayer_one_vs_all
    bias: False
    alpha_tol: 1e-4

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False

grid:
  
  data_params:
    dataset:
      type: choice
      options:
      - cora_ml_cont_auto

  model_params:

    pred_method:
      type: choice
      options:
      - svm

    regularizer:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.03
      - 0.04
      - 0.05
      - 0.055
      - 0.0575
      - 0.06
      - 0.075
      - 0.1
      - 0.15
      - 1
      - 5
      - 10

    skip_connection:
      type: choice
      options:
      # - skip_alpha_relu
      - skip_alpha_linear
    
    skip_alpha:
      type: choice
      options:
      - 0.1
      - 0.2
      - 0.3
      - 0.5
  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 10
          step: 1

