seml:
  name: m_ntk_svm_hyperparam
  executable: exp_ntk_svm_hyperparam.py
  project_root_dir: ../..
  output_dir: m_log/m_ntk_svm_hyperparam

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: phdcpu      
    partition: cpu
    gres: gpu:0       # num gpu
    mem: 20G          # memory
    cpus-per-task: 1  # num cores
    time: 0-08:30     # max time, D-HH:MM
    exclude: gpu12

fixed:
  data_params:
    dataset: csbm
    learning_setting: transductive
    cv_folds: 4
    specification:
      classes: 2
      n_trn_labeled: 40
      n_trn_unlabeled: 0
      n_val: 40
      n_test: 120
      sigma: 1
      avg_within_class_degree: 6.32 #3.16 # 1.58 * 2
      avg_between_class_degree: 1.48 #0.74 #0.37 * 2
      K: 1.5
      seed: 0
    

  model_params:
    label: GCN
    model: GCN
    normalization: row_normalization
    activation: relu
    depth: 1
    pred_method: svm
    bias: False
    solver: qplayer
    alpha_tol: 1e-4
    cache_size: 10000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False

grid:
  # data_params:
  #   K:
  #     type: choice
  #     options:
  #     - 0.1
  #     - 0.5
  #     - 1
  #     - 1.5
  #     - 2
  #     - 3
  #     - 4
  #     - 5
  #   avg_within_class_degree:
  #     type: choice
  #     options:
  #     - 1.58*2
  #   avg_between_class_degree:
  #     type: choice
  #     options:
  #     - 0.37*2

  model_params:
    regularizer:
      type: choice
      options:
      - 0.0001
      - 0.001
      # - 0.005
      # - 0.01
      # - 0.05
      # - 0.1
      # - 0.5
      # - 1
      # - 2
      # - 5
      # - 10
      # - 50
      # - 100
      # - 1000
    
  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 10
          step: 1

