seml:
  name: ntk_gcn_skipalpha_hyperparams
  executable: exp_ntk_hyperparam.py
  project_root_dir: ../..
  output_dir: log/hyperparam

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: studentpriocpu      
    partition: cpu,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-03:00     # max time, D-HH:MM
    exclude: gpu19,mdsi-gpu02

fixed:
  data_params:
    learning_setting: transductive
    specification:
      classes: 2
      n_trn_labeled: 40
      n_trn_unlabeled: 0
      n_val: 40
      n_test: 120
      sigma: 1
      avg_within_class_degree: 3.16
      avg_between_class_degree: 0.74

  model_params:
    label: GCN_skipalpha
    model: GCN
    pred_method: svm
    activation: relu
    solver: qplayer
    alpha_tol: 1e-4
    bias: False

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: sabanaya
    debug: True

grid:
  model_params:
    normalization:
      type: choice
      options:
      - row_normalization
      - sym_normalization

    depth:
      type: choice
      options:
      - 1
      - 2
      - 4
    
    skip_connection:
      type: choice
      options:
      - skip_alpha_linear
      - skip_alpha_relu
    
    skip_alpha:
      type: choice
      options:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5

    regularizer:
      type: choice
      options:
      - 0.001
      - 0.01
      - 0.1
      - 1


seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 10
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 10
      step: 1
      zip_id: seed_opt

