seml:
  name: sbm_hyper_gcn_pc
  executable: exp_ntk_hyperparam.py
  project_root_dir: ../..
  output_dir: log/hyperparam

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-05:00     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17,gpu21

fixed:
  data_params:
    learning_setting: transductive
    specification:
      classes: 2
      n_trn_labeled: 10
      n_trn_unlabeled: 0
      n_val: 10
      n_test: 180
      sigma: 1
      avg_within_class_degree: 3.16
      avg_between_class_degree: 0.74

  model_params:
    label: GCN_skippc
    model: GCN
    pred_method: svm
    activation: relu
    solver: qplayer
    alpha_tol: 1e-4
    bias: False

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: sabanaya

grid:
  model_params:
    normalization:
      type: choice
      options:
      - row_normalization
      - sym_normalization

    depth:
      type: choice
      options:
      - 1
      - 2
      - 4
    
    skip_connection:
      type: choice
      options:
      - skip_pc_linear
      - skip_pc_relu

    regularizer:
      type: choice
      options:
      - 0.001
      - 0.005
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
      - 1
      - 5
      - 10


seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 10
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 10
      step: 1
      zip_id: seed_opt

