seml:
  name: wikics_gcn
  executable: exp_ntk_hyperparam.py
  project_root_dir: ../..
  output_dir: log/hyperparam

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 12G          # memory
    cpus-per-task: 1  # num cores
    time: 0-00:15     # max time, D-HH:MM

fixed:
  data_params:
    learning_setting: transductive
    cv_folds: 4
    specification:
      fraction_test: 0.1
      data_dir: ./data
      balance_test: True

  model_params:
    label: GIN
    model: GIN
    activation: relu
    depth: 1
    solver: qplayer
    bias: False
    alpha_tol: 1e-4

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False

grid:
  
  data_params:
    dataset:
      type: choice
      options:
      - wikics_binary

    specification:
      n_per_class: 
        type: choice
        options:
        - 5

  model_params:

    pred_method:
      type: choice
      options:
      - svm

    regularizer:
      type: choice
      options:
      - 0.02
      - 0.025
      - 0.03
      - 0.04
      - 0.05
      - 0.06
      - 0.07
      - 0.075
      - 0.08
      - 0.09
  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 3
          step: 1

