seml:
  name: get_y
  executable: exp_ntk_certify_label_multiclass_onenode_inexact.py
  project_root_dir: ../..
  output_dir: log/cache

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 6G          # memory
    cpus-per-task: 1  # num cores
    time: 0-00:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: citeseer
    learning_setting: transductive
    specification:
      n_per_class: 10
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    use_tight_big_M: 1
    IntegralityFocus: 1
    Presolve: 2
    epsilon: 0.001
    Threads: 2
    TimeLimit: 259200
      
  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  certificate_params:
    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.03
      - 0.05
      - 0.1

    target_idx:
      type: range
      min: 0
      max: 50
      step: 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 3
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 3
    step: 1
    zip_id: seed_opt

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.0001
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False
