seml:
  name: cs
  executable: exp_ntk_certify_label_multiclass_onenode.py
  project_root_dir: ../..
  output_dir: log/label

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 6G          # memory
    cpus-per-task: 2  # num cores
    time: 0-00:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: citeseer
    learning_setting: transductive
    specification:
      n_per_class: 10
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    use_tight_big_M: 1
    IntegralityFocus: 1
    Presolve: 2
    epsilon: 0.001
    Threads: 2
    TimeLimit: 259200
      
  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  certificate_params:
    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.03
      - 0.05
      - 0.1

    target_idx:
      type: range
      min: 0
      max: 50
      step: 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 3
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 3
    step: 1
    zip_id: seed_opt

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.0001
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

sgc:
  fixed:
    model_params:
      label: SGC
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.0001
      pred_method: svm
      activation: linear
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

appnp:
  fixed:
    model_params:
      label: APPNP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.002
      iteration: 10
      alpha: 0.2
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

mlp:
  fixed:
    model_params:
      label: MLP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.0025
      iteration: 10
      alpha: 1
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False


gin:
  fixed:
    model_params:
      label: GIN
      model: GIN
      depth: 1
      regularizer: 0.00075
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False


graphsage:
  fixed:
    model_params:
      label: GraphSAGE
      model: GCN
      activation: relu
      regularizer: 0.00025
      normalization: graph_sage_normalization
      depth: 1
      solver: qplayer_one_vs_all
      bias: False
      alpha_tol: 1e-4

graphsagev2:
  fixed:
    model_params:
      label: GraphSAGE_v2
      model: GCN
      activation: relu
      regularizer: 0.0005
      normalization: graph_sage_normalization
      depth: 1
      solver: qplayer_one_vs_all
      bias: False
      alpha_tol: 1e-4


gcn_skipalpha:
  fixed:
    model_params:
      label: GCN_skipalpha
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.0001
      skip_connection: skip_alpha_linear
      skip_alpha: 0.5
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False


gcn_skippc:
  fixed:
    model_params:
      label: GCN_skippc
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.0001
      skip_connection: skip_pc_linear
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

gcn_sym:
  fixed:
    model_params:
      label: GCN_sym
      model: GCN
      normalization: sym_normalization
      depth: 1
      regularizer: 0.003
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False


sgc_sym:
  fixed:
    model_params:
      label: SGC_sym
      model: GCN
      normalization: sym_normalization
      depth: 1
      regularizer: 0.0001
      pred_method: svm
      activation: linear
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False