seml:
  name: mlb_label
  executable: exp_ntk_certify_label.py
  project_root_dir: ../..
  output_dir: log/label

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 4-00:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: cora_ml_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True
      
  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  certificate_params:
    use_tight_big_M:
      type: choice
      options:
      - 1
      - 0
    
    IntegralityFocus:
      type: choice
      options:
      - 1
      - 0

    delta:
      type: choice
      options:
      - 0.05 # 1
      - 0.15 # 3
      - 0.25 # 5

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.075
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False
