seml:
  name: label_sgc
  executable: exp_ntk_certify_label.py
  project_root_dir: ../..
  output_dir: log/label

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 2  # num cores
    time: 4-20:30     # max time, D-HH:MM
    exclude: gpu13,gpu14,gpu16,gpu17

fixed:
  data_params:
    learning_setting: transductive
    specification:
      classes: 2
      n_trn_labeled: 20
      n_trn_unlabeled: 0
      n_val: 20
      n_test: 160
      sigma: 1
      avg_within_class_degree: 3.16
      avg_between_class_degree: 0.74

  model_params:
    model: GCN
    normalization: row_normalization
    pred_method: svm
    activation: linear
    solver: qplayer
    alpha_tol: 1e-4
    bias: False

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: sabanaya

grid:
  
  model_params:
    label:
      type: choice
      options:
      - SGC
      - SGC_depth2
      - SGC_depth4
      zip_id: depths

    depth:
      type: choice
      options:
      - 1
      - 2
      - 4
      zip_id: depths

    regularizer:
      type: choice
      options:
      - 0.001
      - 0.01
      # - 0.1
      #- 1

  certificate_params:
    delta:
      type: choice
      options:
      # - 0.01 # 0 for 80 # 0 for 40
      # - 0.02 # 1  # 0
      - 0.03 # 2 # 1
      - 0.05 # 4 # 2
      - 0.1 # 8 # 4
      - 0.15 # 12 # 6
      - 0.2 # 16 # 8
      - 0.25 # 20 # 10
      - 0.3 # 24 # 12
      - 0.4 # 32 # 16
      - 0.5 # 40 # 20
      - 1 # 80 # 40

  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 5
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 5
      step: 1
      zip_id: seed_opt

