seml:
  name: bin_pu_att_linf
  executable: exp_ntk_attack.py
  project_root_dir: ../..
  output_dir: log/attack

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: phdcpu      
    partition: cpu,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 1-05:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: cora_ml_cont_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  attack_params:
    attack: apgd
    max_iter: 100
    method: XXT
    perturbation_model: linf
    normalize_grad: True
    attack_nodes: test
    n_attack: 100
    delta_absolute: True

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    store_first_iter: 5
    store_attack_curve: False

grid:

  attack_params:
    eta:
      type: choice
      options:
      - 2

    n_adversarial:
      type: choice
      options:
      - 12
      - 24
      - 60
      #- 121
      #- 243
      #- 607
      #- 1215

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt


gcn:
  fixed:
    model_params:
      label: GCN_att
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.75
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sgc:
  fixed:
    model_params:
      label: SGC_att
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.75
      pred_method: svm
      activation: linear
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

appnp:
  fixed:
    model_params:
      label: APPNP_alpha0.2_att
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 1
      iteration: 10
      alpha: 0.2
      solver: qplayer
      alpha_tol: 1e-4
      bias: False