seml:
  name: sbm_attack
  executable: exp_ntk_attack.py
  project_root_dir: ../..
  output_dir: log/attack

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-10:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17,gpu21

fixed:
  data_params:
    learning_setting: transductive
    specification:
      n_per_class: 2
      n_trn_labeled: 40
      n_trn_unlabeled: 0
      n_val: 40
      n_test: 120
      sigma: 1
      avg_within_class_degree: 3.16
      avg_between_class_degree: 0.74

  attack_params:
    attack: apgd
    max_iter: 300
    method: XXT
    perturbation_model: linf
    attack_nodes: test
    delta_absolute: False

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    store_first_iter: 5
    store_attack_curve: False

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      # - l2
      - linf

    n_adversarial:
      type: choice
      options:
      - 1
      - 2
      - 6
      - 12
      - 24
      - 60
      - 120

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
    
  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.01
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sgc:
  fixed:
    model_params:
      label: SGC
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.01
      pred_method: svm
      activation: linear
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

mlp:
  fixed:
    model_params:
      label: MLP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      iteration: 10
      alpha: 1
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_skipalpha:
  fixed:
    model_params:
      label: GCN_skipalpha
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.01
      skip_connections: skip_alpha_linear
      skip_alpha: 0.2
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_skippc:
  fixed:
    model_params:
      label: GCN_skippc
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.01
      skip_connections: skip_pc_linear
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False
