seml:
  name: ntk_gsage_att
  executable: exp_ntk_attack.py
  project_root_dir: ../..
  output_dir: log/attack

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: deadline
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-10:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17,gpu21

fixed:
  data_params:
    learning_setting: transductive
    specification:
      classes: 2
      n_trn_labeled: 40
      n_trn_unlabeled: 0
      n_val: 40
      n_test: 120
      sigma: 1
      avg_within_class_degree: 3.16
      avg_between_class_degree: 0.74

  model_params:
    label: GraphSAGE
    model: GCN
    normalization: graph_sage_normalization
    depth: 1
    pred_method: svm
    activation: relu
    solver: qplayer
    alpha_tol: 1e-4
    bias: False

  attack_params:
    attack: apgd
    max_iter: 300
    method: XXT
    perturbation_model: linf
    normalize_grad: False
    attack_nodes: test
    delta_absolute: False

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    store_first_iter: 5
    store_attack_curve: False

grid:
  
  model_params:
    regularizer:
      type: choice
      options:
      - 0.01

  attack_params:
    eta:
      type: choice
      options:
      - 10

    n_adversarial:
      type: choice
      options:
      - 1
      - 2
      - 6
      - 12
      - 24
      - 60
      - 120
      # - 1
      # - 2
      # - 4
      # - 8
      # - 16
      # - 40
      # - 80

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 5
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 5
      step: 1
      zip_id: seed_opt

