seml:
  name: cb_coll_50_depth_test
  executable: exp_ntk_certify_collective_label.py
  project_root_dir: ../..
  output_dir: log/label_collect

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: deadline
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 11G          # memory
    cpus-per-task: 4  # num cores
    time: 0-05:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: citeseer_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True
  
  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    use_tight_big_M: 1
    SoftMemLimit: 10
    Presolve: 2
    MILP_OPTIMALITY_TOL: 1e-6
    Threads: 4
    TimeLimit: 18000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:

  certificate_params:
    IntegralityFocus: 
      type: choice
      options:
      - 0
      - 1

    NumericFocus: 
      type: choice
      options:
      - 0
      - 1  
      - 2
      - 3

    MILP_INT_FEAS_TOL:
      type: choice
      options:
      - 1e-4
      - 1e-5
      zip_id: tol
    
    MILP_FEAS_TOL:
      type: choice
      options:
      - 1e-5
      - 1e-6
      zip_id: tol

    n_test:
      type: choice
      options:
      - 50

    delta:
      type: choice
      options:
      - 0.05

  data_params:
    specification:
      seed:
        type: range
        min: 1
        max: 2
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 1
    max: 2
    step: 1
    zip_id: seed_opt


gcn_l2:
  fixed:
    model_params:
      label: GCN_L2
      model: GCN
      normalization: row_normalization
      depth: 2
      regularizer: 2.5
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False
