seml:
  name: mlb_coll
  executable: exp_certify_label_collective.py
  project_root_dir: ../..
  output_dir: log/label_collect

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0       # num gpu
    mem: 12G          # memory
    cpus-per-task: 2  # num cores
    time: 1-05:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora_ml_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True
  
  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    use_tight_big_M: 1
    IntegralityFocus: 1
    Presolve: 2
    Threads: 2
    TimeLimit: 86400

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /path/to/gurobi.lic

grid:

  certificate_params:
    n_test:
      type: choice
      options:
      - 50

    delta:
      type: choice
      options:
      - 0.05
      - 0.1
      - 0.15 
      - 0.2
      - 0.25
      - 0.3
      - 0.4
      - 0.5
      - 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt


gcn_weigh0_25:
  fixed:
    model_params:
      label: GCN_weigh0.25
      model: GCN
      normalization: row_normalization
      depth: 1
      weigh_adjacency: 0.25
      regularizer: 0.05
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False
      
gcn_weigh0_50:
  fixed:
    model_params:
      label: GCN_weigh0.5
      model: GCN
      normalization: row_normalization
      depth: 1
      weigh_adjacency: 0.5
      regularizer: 0.075
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_weigh0_75:
  fixed:
    model_params:
      label: GCN_weigh0.75
      model: GCN
      normalization: row_normalization
      depth: 1
      weigh_adjacency: 0.75
      regularizer: 0.075
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False