seml:
  name: coll_test
  executable: exp_ntk_certify_collective_label.py
  project_root_dir: ../..
  output_dir: log/label_collect

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 20G          # memory
    cpus-per-task: 2  # num cores
    time: 0-13:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: cora_ml_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  model_params:
    label: GCN
    model: GCN
    normalization: row_normalization
    depth: 1
    regularizer: 0.075
    pred_method: svm
    activation: relu
    solver: qplayer
    alpha_tol: 1e-4
    bias: False

  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    IntegralityFocus: 1
    use_tight_big_M: 1
    TimeLimit: 43200
    n_test: 50

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:

  certificate_params:
    delta:
      type: choice
      options:
      - 0.05 # 12 # 6

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 3
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 3
    step: 1
    zip_id: seed_opt


normal:
  fixed:
    certificate_params:
      DualReductions: 0

dual:
  fixed:
    certificate_params:
      DualReductions: 1

presolve:
  fixed:
    certificate_params:
      IntegralityFocus: 1
      DualReductions: 0
      Presolve: 2

cuts2:
  fixed:
    certificate_params:
      IntegralityFocus: 1
      DualReductions: 0
      Cuts: 2

cuts3:
  fixed:
    certificate_params:
      IntegralityFocus: 1
      DualReductions: 0
      Cuts: 3
