seml:
  name: mlb_coll
  executable: exp_labelcert_collective.py
  project_root_dir: ../..
  output_dir: log/label_collect

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0       # num gpu
    mem: 12G          # memory
    cpus-per-task: 2  # num cores
    time: 3-05:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora_ml_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True
  
  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    use_tight_big_M: 1
    IntegralityFocus: 1
    TimeLimit: 259200

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /path/to/gurobi.lic

grid:

  certificate_params:
    n_test:
      type: choice
      options:
      - 50

    delta:
      type: choice
      options:
      - 0.05
      - 0.1
      - 0.15 
      - 0.2
      - 0.25
      - 0.3
      - 0.4
      - 0.5
      - 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt


gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.075
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sgc:
  fixed:
    model_params:
      label: SGC
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.075
      pred_method: svm
      activation: linear
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

mlp:
  fixed:
    model_params:
      label: MLP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.025
      iteration: 10
      alpha: 1
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

graphsage:
  fixed:
    model_params:
      label: GraphSAGE
      model: GCN
      activation: relu
      regularizer: 0.0075
      normalization: graph_sage_normalization
      depth: 1
      solver: qplayer
      bias: False
      alpha_tol: 1e-4

gcn_skipalpha:
  fixed:
    model_params:
      label: GCN_skipalpha
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.1
      skip_connection: skip_alpha_linear
      skip_alpha: 0.1
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_skippc:
  fixed:
    model_params:
      label: GCN_skippc
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.075
      skip_connection: skip_pc_linear
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_sym:
  fixed:
    model_params:
      label: GCN_sym
      model: GCN
      normalization: sym_normalization
      depth: 1
      regularizer: 0.075
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sgc_sym:
  fixed:
    model_params:
      label: SGC_sym
      model: GCN
      normalization: sym_normalization
      depth: 1
      regularizer: 0.05
      pred_method: svm
      activation: linear
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

appnp:
  fixed:
    model_params:
      label: APPNP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.5
      iteration: 10
      alpha: 0
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gin:
  fixed:
    model_params:
      label: GIN
      model: GIN
      depth: 1
      regularizer: 0.025
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False