seml:
  name: label_sbm
  executable: exp_labelcert_collective.py
  project_root_dir: ../..
  output_dir: log/label_collect

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0       # num gpu
    mem: 30G          # memory
    cpus-per-task: 2  # num cores
    time: 1-10:30     # max time, D-HH:MM


fixed:
  data_params:
    learning_setting: transductive
    specification:
      classes: 2
      n_trn_labeled: 10
      n_trn_unlabeled: 0
      n_val: 10
      n_test: 180
      sigma: 1
      # avg_within_class_degree: 3.16 
      # avg_between_class_degree: 0.74 

  certificate_params:
    TimeLimit: 86400
    LogToConsole: 1
    OutputFlag: 1
    Threads: 2
    Presolve: 2

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: path/to/your/gurobi/license

grid:

  certificate_params:
    delta:
      type: choice
      options:
      - 0.05 # 1
      - 0.1 # 2
      - 0.15 # 3
      - 0.2 # 4
      - 0.25 # 5
      - 0.3 # 6
      - 0.5 # 10
      - 1 # 20
  
  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt

# gcn:
#   fixed:
#     model_params:
#       label: GCN
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# sgc:
#   fixed:
#     model_params:
#       label: SGC
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_skipalpha:
#   fixed:
#     model_params:
#       label: GCN_skipalpha_linear
#       model: GCN
#       normalization: sym_normalization
#       skip_connection: skip_alpha_linear
#       skip_alpha: 0.1
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_skippc:
#   fixed:
#     model_params:
#       label: GCN_skippc_linear
#       model: GCN
#       normalization: row_normalization
#       skip_connection: skip_pc_linear
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# mlp:
#   fixed:
#     model_params:
#       label: MLP
#       model: APPNP
#       activation: relu
#       normalization: sym_normalization
#       regularizer: 0.001
#       iteration: 10
#       alpha: 1
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# appnp:
#   fixed:
#     model_params:
#       label: APPNP_0.1
#       model: APPNP
#       activation: relu
#       normalization: sym_normalization
#       regularizer: 0.5
#       iteration: 10
#       alpha: 0.1
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gin:
#   fixed:
#     model_params:
#       label: GIN
#       model: GIN
#       normalization: no_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# graphsage:
#   fixed:
#     model_params:
#       label: GraphSAGE
#       model: GCN
#       normalization: graph_sage_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_d2:
#   fixed:
#     model_params:
#       label: GCN_depth2
#       model: GCN
#       normalization: row_normalization
#       depth: 2
#       regularizer: 0.25
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_d4:
#   fixed:
#     model_params:
#       label: GCN_depth4
#       model: GCN
#       normalization: row_normalization
#       depth: 4
#       regularizer: 0.25
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False


# sgc_d2:
#   fixed:
#     model_params:
#       label: SGC_depth2
#       model: GCN
#       normalization: row_normalization
#       depth: 2
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# sgc_d4:
#   fixed:
#     model_params:
#       label: SGC_depth4
#       model: GCN
#       normalization: row_normalization
#       depth: 4
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# # gin_d2:
# #   fixed:
# #     model_params:
# #       label: GIN_depth2
# #       model: GIN
# #       normalization: no_normalization
# #       depth: 2
# #       regularizer: 0.001
# #       pred_method: svm
# #       activation: relu
# #       solver: qplayer
# #       alpha_tol: 1e-4
# #       bias: False

# # gin_d4:
# #   fixed:
# #     model_params:
# #       label: GIN_depth4
# #       model: GIN
# #       normalization: no_normalization
# #       depth: 4
# #       regularizer: 0.001
# #       pred_method: svm
# #       activation: relu
# #       solver: qplayer
# #       alpha_tol: 1e-4
# #       bias: False

# graphsage_d2:
#   fixed:
#     model_params:
#       label: GraphSAGE_depth2
#       model: GCN
#       normalization: graph_sage_normalization
#       depth: 2
#       regularizer: 0.005
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# graphsage_d4:
#   fixed:
#     model_params:
#       label: GraphSAGE_depth4
#       model: GCN
#       normalization: graph_sage_normalization
#       depth: 4
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_skippc_d2:
#   fixed:
#     model_params:
#       label: GCN_skippc_linear_depth2
#       model: GCN
#       normalization: row_normalization
#       skip_connection: skip_pc_linear
#       depth: 2
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_skippc_d4:
#   fixed:
#     model_params:
#       label: GCN_skippc_linear_depth4
#       model: GCN
#       normalization: row_normalization
#       skip_connection: skip_pc_linear
#       depth: 4
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_skipalpha_d2:
#   fixed:
#     model_params:
#       label: GCN_skipalpha_linear_depth2
#       model: GCN
#       normalization: sym_normalization
#       skip_connection: skip_alpha_linear
#       depth: 2
#       skip_alpha: 0.1
#       regularizer: 0.25
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_skipalpha_d4:
#   fixed:
#     model_params:
#       label: GCN_skipalpha_linear_depth4
#       model: GCN
#       normalization: sym_normalization
#       skip_connection: skip_alpha_linear
#       skip_alpha: 0.2
#       depth: 4
#       regularizer: 0.5
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# appnp_2:
#   fixed:
#     model_params:
#       label: APPNP_0.2
#       model: APPNP
#       activation: relu
#       normalization: sym_normalization
#       regularizer: 0.25
#       iteration: 10
#       alpha: 0.2
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# appnp_3:
#   fixed:
#     model_params:
#       label: APPNP_0.3
#       model: APPNP
#       activation: relu
#       normalization: sym_normalization
#       regularizer: 0.1
#       iteration: 10
#       alpha: 0.3
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# appnp_5:
#   fixed:
#     model_params:
#       label: APPNP_0.5
#       model: APPNP
#       activation: relu
#       normalization: sym_normalization
#       regularizer: 0.001
#       iteration: 10
#       alpha: 0.5
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# appnp_0:
#   fixed:
#     model_params:
#       label: APPNP_0
#       model: APPNP
#       activation: relu
#       normalization: sym_normalization
#       regularizer: 5
#       iteration: 10
#       alpha: 0.0
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_2x:
#   fixed:
#     data_params:
#       specification:
#         avg_within_class_degree: 6.32
#         avg_between_class_degree: 1.48

#     model_params:
#       label: GCN_sparsity_1
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.5
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# gcn_05x:
#   fixed:
#     data_params:
#       specification:
#         avg_within_class_degree: 1.58
#         avg_between_class_degree: 0.37

#     model_params:
#       label: GCN_sparsity_2
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: relu
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# sgc_2x:
#   fixed:
#     data_params:
#       specification:
#         avg_within_class_degree: 6.32
#         avg_between_class_degree: 1.48

#     model_params:
#       label: SGC_sparsity_1
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# sgc_05x:
#   fixed:
#     data_params:
#       specification:
#         avg_within_class_degree: 1.58
#         avg_between_class_degree: 0.37

#     model_params:
#       label: SGC_sparsity_2
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

gcn_2homo:
  fixed:
    data_params:
      specification:
        avg_within_class_degree: 6.32
        avg_between_class_degree: 0.74

    model_params:
      label: GCN_homophily_1
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.001
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_05homo:
  fixed:
    data_params:
      specification:
        avg_within_class_degree: 1.58
        avg_between_class_degree: 0.74

    model_params:
      label: GCN_homophily_2
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.001
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

# sgc_2homo:
#   fixed:
#     data_params:
#       specification:
#         avg_within_class_degree: 6.32
#         avg_between_class_degree: 0.74

#     model_params:
#       label: SGC_homophily_1
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False

# sgc_05homo:
#   fixed:
#     data_params:
#       specification:
#         avg_within_class_degree: 1.58
#         avg_between_class_degree: 0.74

#     model_params:
#       label: SGC_homophily_2
#       model: GCN
#       normalization: row_normalization
#       depth: 1
#       regularizer: 0.001
#       pred_method: svm
#       activation: linear
#       solver: qplayer
#       alpha_tol: 1e-4
#       bias: False