seml:
  name: ml_n5
  executable: exp_labelcert_multiclass_onenode.py
  project_root_dir: ../..
  output_dir: log/label

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0       # num gpu
    mem: 12G          # memory
    cpus-per-task: 2  # num cores
    time: 3-05:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora_ml
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    LogToConsole: 1
    OutputFlag: 1
    use_tight_big_M: 1
    IntegralityFocus: 1
    Presolve: 2
    Threads: 2
    TimeLimit: 43200
      
  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /path/to/gurobi.lic

grid:
  certificate_params:
    delta:
      type: choice
      options:
      - 0.02
      - 0.03
      - 0.05
      - 0.1

    target_idx:
      type: range
      min: 0
      max: 50
      step: 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 3
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 3
    step: 1
    zip_id: seed_opt

sgc:
  fixed:
    model_params:
      label: SGC
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.004
      pred_method: svm
      activation: linear
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.004
      pred_method: svm
      activation: linear
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

gcn_skipalpha:
  fixed:
    model_params:
      label: GCN_skipalpha
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.004
      skip_connection: skip_alpha_linear
      skip_alpha: 0.2
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_skippc:
  fixed:
    model_params:
      label: GCN_skippc
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.003
      skip_connection: skip_pc_linear
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False
