seml:
  name: l1_bin_pu_cert
  executable: exp_qpcert.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-05:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora_ml_cont_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    method: XXT
    delta_absolute: True
    attack_nodes: train_val
    NumericFocus: 0
    MIPFocus: 0
    LogToConsole: 0
    OutputFlag: 0
    TimeLimit: 100000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /path/to/gurobi.lic

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      - l1

    n_adversarial:
      type: choice
      options:
      - 1
      - 2
      - 4
      - 10
      - 20

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1

mlp:
  fixed:
    model_params:
      model: APPNP
      activation: relu
      normalization: sym_normalization
      iteration: 10
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

  grid:
    model_params:
      label:
        type: choice
        options: 
        - APPNP_alpha0.1

      alpha: 
        type: choice
        options:
        - 0.1

      regularizer: 
        type: choice
        options:
        - 1
        zip_id: appnp

    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 5
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 5
      step: 1
      zip_id: seed_opt