seml:
  name: cora_gcn_cert
  executable: exp_certify_multiclass_onenode.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: phdcpu      
    partition: cpu,cpu_large
    gres: gpu:0       # num gpu
    mem: 12G          # memory
    cpus-per-task: 4  # num cores
    time: 3-20:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora
    learning_setting: transductive
    specification:
      n_per_class: 10
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True


  model_params:
    label: GCN
    model: GCN
    normalization: row_normalization
    depth: 1
    pred_method: svm
    activation: relu
    solver: qplayer_one_vs_all
    alpha_tol: 1e-4
    bias: False

  certificate_params:
    n_targets_per_class: 10
    method: XXT
    perturbation_model: l2
    attack_nodes: test
    NumericFocus: 0
    TimeLimit: 86400

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  
  model_params:
    regularizer:
      type: choice
      options:
      #- 0.001
      #- 0.002
      #- 0.003
      #- 0.004
      #- 0.005
      #- 0.0075
      zip_id: output
    

  certificate_params:
    LogToConsole: 
      type: choice
      options:
      #- 0
      - 0
      #- 0
      #- 1
      #- 1
      zip_id: output

    OutputFlag: 
      type: choice
      options:
      #- 0
      #- 0
      - 0
      #- 1
      #- 1
      zip_id: output

    n_adversarial:
      type: choice
      options:
      #- 25 
      #- 51
      #- 128
      - 256
      #- 513
      #- 1284
      #- 2568

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
    
    target_idx:
      type: range
      min: 0
      max: 70
      step: 1
  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 3
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 3
      step: 1
      zip_id: seed_opt

