seml:
  name: mlcont_pl
  executable: exp_certify_multiclass_onenode.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 25G          # memory
    cpus-per-task: 2  # num cores
    time: 4-06:30     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: cora_ml_cont_auto
    learning_setting: transductive
    specification:
      n_per_class: 10
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    method: XXT
    delta_absolute: True
    attack_nodes: train_val
    NumericFocus: 0
    MIPFocus_first: 0
    MIPFocus_other: 0
    LogToConsole: 0
    OutputFlag: 0
    TimeLimit: 64800

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      - l2

    n_adversarial:
      type: choice
      options:
      - 140

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      #- 0.1
      #- 0.2
      #- 0.5
      #- 1

    target_idx:
      type: range
      min: 0
      max: 35
      step: 1
    
  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 3
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 3
    step: 1
    zip_id: seed_opt

gcn:
  fixed:
    model_params:
      label: APPNP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.15
      iteration: 10
      alpha: 0.2
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False
