seml:
  name: bin_bl_l1
  executable: exp_certify_backdoor.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options: 
    gres: gpu:0       # num gpu
    mem: 5G          # memory
    cpus-per-task: 1  # num cores
    time: 0-02:00     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora_ml_cont_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    method: XXT
    delta_absolute: True
    attack_nodes: train_val_backdoor
    n_backdoor_evals: 100
    NumericFocus: 0
    MIPFocus: 0
    LogToConsole: 0
    OutputFlag: 0
    TimeLimit: 100000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /path/to/gurobi.lic

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      - l1

    n_adversarial:
      type: choice
      options:
      - 1
      - 2
      - 4
      - 10
      - 20

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
    
  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.75
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_sym:
  fixed:
    model_params:
      label: GCN_sym
      model: GCN
      normalization: sym_normalization
      depth: 1
      regularizer: 1
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sgc:
  fixed:
    model_params:
      label: SGC
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.75
      pred_method: svm
      activation: linear
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sgc_sym:
  fixed:
    model_params:
      label: SGC_sym
      model: GCN
      normalization: sym_normalization
      depth: 1
      regularizer: 0.75
      pred_method: svm
      activation: linear
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

mlp:
  fixed:
    model_params:
      label: MLP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.5
      iteration: 10
      alpha: 1
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_skipalpha:
  fixed:
    model_params:
      label: GCN_skipalpha
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 1
      skip_connection: skip_alpha_linear
      skip_alpha: 0.1
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gcn_skippc:
  fixed:
    model_params:
      label: GCN_skippc
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.5
      skip_connection: skip_pc_linear
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

gin:
  fixed:
    model_params:
      label: GIN
      model: GIN
      depth: 1
      regularizer: 0.05
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sage:
  fixed:
    model_params:
      label: GraphSAGE
      model: GCN
      activation: relu
      regularizer: 0.1
      normalization: graph_sage_normalization
      depth: 1
      solver: qplayer
      bias: False
      alpha_tol: 1e-4

appnp:
  fixed:
    model_params:
      label: APPNP_alpha0.1
      model: APPNP
      activation: relu
      normalization: sym_normalization
      alpha: 0.1
      regularizer: 1
      iteration: 10
      solver: qplayer
      alpha_tol: 1e-4
      bias: False