seml:
  name: bin_bu_cert
  executable: exp_certify_backdoor_realbinary.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 5G          # memory
    cpus-per-task: 1  # num cores
    time: 0-02:00     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: cora_ml_cont_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    method: XXT
    delta_absolute: True
    attack_nodes: test_backdoor
    n_backdoor_evals: 100
    NumericFocus: 0
    MIPFocus: 0
    LogToConsole: 0
    OutputFlag: 0
    TimeLimit: 100000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      - l2
      #- linf

    n_adversarial:
      type: choice
      options:
      - 11
      - 22
      - 55
      - 111
      - 223
      - 557
      - 1115

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
    
  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt

gin:
  fixed:
    model_params:
      label: GIN
      model: GIN
      depth: 1
      regularizer: 0.05
      pred_method: svm
      activation: relu
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

sage:
  fixed:
    model_params:
      label: GraphSAGE
      model: GCN
      activation: relu
      regularizer: 0.1
      normalization: graph_sage_normalization
      depth: 1
      solver: qplayer
      bias: False
      alpha_tol: 1e-4