seml:
  name: bin_bu_appnp_cert
  executable: exp_certify_backdoor_coramlb.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: phdcpu      
    partition: cpu,cpu_large
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-02:00     # max time, D-HH:MM
    exclude: gpu14,gpu16,gpu17

fixed:
  data_params:
    dataset: cora_ml_cont_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    method: XXT
    delta_absolute: True
    attack_nodes: test_backdoor
    n_backdoor_evals: 100
    NumericFocus: 0
    MIPFocus: 0
    LogToConsole: 0
    OutputFlag: 0
    TimeLimit: 100000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /path/to/your/gurobi/license

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      - l2
      - linf

    n_adversarial:
      type: choice
      options:
      - 11
      - 22
      - 55
      - 111
      - 223
      - 557
      - 1115

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
    
APPNP:
  fixed:
    model_params:
      model: APPNP
      activation: relu
      normalization: sym_normalization
      iteration: 10
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

  grid:
    model_params:
      label:
        type: choice
        options: 
        - APPNP_alpha0
        - APPNP_alpha0.1
        - APPNP_alpha0.2
        - APPNP_alpha0.3
        - APPNP_alpha0.5
        zip_id: appnp

      alpha: 
        type: choice
        options:
        - 0
        - 0.1
        - 0.2
        - 0.3
        - 0.5
        zip_id: appnp

      regularizer: 
        type: choice
        options:
        - 1
        - 1
        - 1
        - 0.75
        - 0.75
        zip_id: appnp

    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 5
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 5
      step: 1
      zip_id: seed_opt

APPNP_row:
  fixed:
    model_params:
      model: APPNP
      activation: relu
      normalization: row_normalization
      iteration: 10
      solver: qplayer
      alpha_tol: 1e-4
      bias: False

  grid:
    model_params:
      label:
        type: choice
        options: 
        - APPNP_alpha0_row
        - APPNP_alpha0.1_row
        - APPNP_alpha0.2_row
        - APPNP_alpha0.3_row
        - APPNP_alpha0.5_row
        zip_id: appnp

      alpha: 
        type: choice
        options:
        - 0
        - 0.1
        - 0.2
        - 0.3
        - 0.5
        zip_id: appnp

      regularizer: 
        type: choice
        options:
        - 1
        - 1
        - 1
        - 0.75
        - 0.75
        zip_id: appnp

    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 5
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 5
      step: 1
      zip_id: seed_opt