seml:
  name: coramlcont_bu
  executable: exp_certify_multiclass_onenode.py
  project_root_dir: ../..
  output_dir: log/certification_multi

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: deadline    
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 25G          # memory
    cpus-per-task: 4  # num cores
    time: 1-05:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: cora_ml_cont_auto
    learning_setting: transductive
    specification:
      n_per_class: 10
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    n_targets_per_class: 5
    method: XXT
    perturbation_model: l2
    attack_nodes: test
    NumericFocus: 0
    MIPFocus_first: 0
    MIPFocus_other: 0
    LogToConsole: 1
    OutputFlag: 1
    Presolve: 2
    Threads: 4
    TimeLimit: 64600

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  certificate_params:
    n_adversarial:
      type: choice
      options:
      #- 28
      - 57
      #- 142
      #- 285
      #- 571
      #- 1427
      #- 2855

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      #- 0.1
      #- 0.2
      #- 0.5
    
    target_idx:
      type: range
      min: 0
      max: 70
      step: 1

  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 3
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 3
    step: 1
    zip_id: seed_opt


sgc:
  fixed:
    model_params:
      label: SGC
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.0575
      pred_method: svm
      activation: linear
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

mlp:
  fixed:
    model_params:
      label: MLP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.004
      iteration: 10
      alpha: 1
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

gcn:
  fixed:
    model_params:
      label: GCN
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.05
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

sage:
  fixed:
    model_params:
      label: GraphSAGE
      model: GCN
      activation: relu
      regularizer: 0.002
      normalization: graph_sage_normalization
      depth: 1
      solver: qplayer_one_vs_all
      bias: False
      alpha_tol: 1e-4

gcnb:
  fixed:
    model_params:
      label: GCN_skippc
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.03
      skip_connection: skip_pc_linear
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

gcna:
  fixed:
    model_params:
      label: GCN_skipalpha
      model: GCN
      normalization: row_normalization
      depth: 1
      regularizer: 0.04
      skip_connection: skip_alpha_linear
      skip_alpha: 0.2
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

appnp:
  fixed:
    model_params:
      label: APPNP
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.15
      iteration: 10
      alpha: 0.2
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False

gin:
  fixed:
    model_params:
      label: GIN
      model: GIN
      depth: 1
      regularizer: 0.0125
      pred_method: svm
      activation: relu
      solver: qplayer_one_vs_all
      alpha_tol: 1e-4
      bias: False
