seml:
  name: ntk_gcn_cert
  executable: exp_ntk_cert_pois.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: phdcpu      
    partition: cpu
    gres: gpu:0       # num gpu
    mem: 10G          # memory
    cpus-per-task: 1  # num cores
    time: 0-20:30     # max time, D-HH:MM
    exclude: gpu12

fixed:
  data_params:
    learning_setting: transductive
    specification:
      classes: 2
      n_trn_labeled: 40
      n_trn_unlabeled: 0
      n_val: 40
      n_test: 10
      sigma: 1
      avg_within_class_degree: 3.16
      avg_between_class_degree: 0.74

  model_params:
    label: GCN
    model: GCN
    normalization: row_normalization
    depth: 1
    pred_method: svm
    activation: relu
    solver: qplayer
    alpha_tol: 1e-4
    bias: False

  certificate_params:
    method: XXT
    perturbation_model: linf
    attack_nodes: test
    delta_absolute: False

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: /ceph/ssd/staff/gosl/app/gurobi.lic

grid:
  
  model_params:
    regularizer:
      type: choice
      options:
      - 0.001
      #- 0.01
      #- 0.1
      #- 1

  certificate_params:
    n_adversarial:
      type: choice
      options:
      - 1
      #- 2
      #- 6
      #- 12
      #- 24
      #- 60
      #- 120

    delta:
      type: choice
      options:
      - 0.01
      #- 0.02
      #- 0.05
      #- 0.1
      #- 0.2
      #- 0.5
      #- 1
  

seeds:
  grid:
    data_params:
      specification:
        seed:
          type: range
          min: 0
          max: 10
          step: 1
          zip_id: seed_opt
    
    seed:
      type: range
      min: 0
      max: 10
      step: 1
      zip_id: seed_opt

