seml:
  name: wb_pl
  executable: exp_ntk_certify.py
  project_root_dir: ../..
  output_dir: log/certification

slurm:
  experiments_per_job: 1
  sbatch_options:
    qos: deadline
    partition: cpu_all,cpu_large
    gres: gpu:0       # num gpu
    mem: 12G          # memory
    cpus-per-task: 1  # num cores
    time: 1-05:30     # max time, D-HH:MM

fixed:
  data_params:
    dataset: wikics_binary
    learning_setting: transductive
    specification:
      n_per_class: 5
      fraction_test: 0.01
      data_dir: ./data
      make_undirected: True
      binary_attr: False
      balance_test: True

  certificate_params:
    method: XXT
    delta_absolute: True
    attack_nodes: train_val
    NumericFocus: 0
    MIPFocus: 0
    LogToConsole: 0
    OutputFlag: 0
    TimeLimit: 100000

  verbosity_params:
    debug_lvl: info

  other_params:
    device: cpu
    dtype: float64
    allow_tf32: False
    path_gurobi_license: lukas

grid:
  
  certificate_params:
    perturbation_model: 
      type: choice 
      options:
      - l2

    n_adversarial:
      type: choice
      options:
      #- 1
      - 2
      #- 4
      #- 10
      - 20

    delta:
      type: choice
      options:
      - 0.01
      - 0.02
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
    
  data_params:
    specification:
      seed:
        type: range
        min: 0
        max: 5
        step: 1
        zip_id: seed_opt
  
  seed:
    type: range
    min: 0
    max: 5
    step: 1
    zip_id: seed_opt

mlp:
  fixed:
    model_params:
      label: MLP_v2
      model: APPNP
      activation: relu
      normalization: sym_normalization
      regularizer: 0.75
      iteration: 10
      alpha: 1
      solver: qplayer
      alpha_tol: 1e-4
      bias: False